INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content1','title1','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content2','title2','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content3','title3','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content4','title4','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content5','title5','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content6','title6','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content7','title7','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content8','title8','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content9','title9','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content10','title10','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content11','title11','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content12','title12','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content13','title13','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content14','title14','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content15','title15','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content16','title16','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content17','title17','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content18','title18','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content19','title19','userName', '1234',now(), now());
INSERT INTO posts (content,title,user_name,pw,create_dt, modify_dt) VALUES ('content20','title20','userName', '1234',now(), now());
INSERT INTO users (password, user_name) VALUES('12345678', 'tester');
INSERT INTO users (password, user_name) VALUES('12345678!', 'userName');

insert into comments(create_dt, modify_dt, post_id, comment, user_name) values (now(), now(), 4, "comment1", "userName");
insert into comments(create_dt, modify_dt, post_id, comment, user_name) values (now(), now(), 4, "comment2", "userName");
insert into comments(create_dt, modify_dt, post_id, comment, user_name) values (now(), now(), 4, "comment3", "userName");
insert into comments(create_dt, modify_dt, post_id, comment, user_name) values (now(), now(), 5, "comment4", "userName");
insert into comments(create_dt, modify_dt, post_id, comment, user_name) values (now(), now(), 5, "comment5", "userName");
insert into comments(create_dt, modify_dt, post_id, comment, user_name) values (now(), now(), 5, "comment6", "userName");
insert into comments(create_dt, modify_dt, post_id, comment, user_name) values (now(), now(), 5, "comment7", "userName");